# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b2b1ef0373a3d22f6ce611090978f775872d899889e910a0f94b2541020861563c5cd7e41dc9174fd4ff22dcc53d0e1230a0d768192b6b2758b294f9d3f621

test:
  secret_key_base: 799475889461fbce98e12fac346222cd72b43f3fbb61739f51fbc2c3e69ac1a25e9d5541eeee0f391b8db6f5c446e47dc95239fb6828012d5348d4cd66fded89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
